
export const MODAL_OPEN_COMPOSE_TOOT = 'MODAL_OPEN_COMPOSE_TOOT';
export const MODAL_OPEN_DELETE_TOOT  = 'MODAL_OPEN_DELETE_TOOT';
export const MODAL_OPEN_STATUS       = 'MODAL_OPEN_STATUS';
export const MODAL_OPEN_MEDIA        = 'MODAL_OPEN_MEDIA';
export const MODAL_OPEN_MEDIA_STATUS = 'MODAL_OPEN_MEDIA_STATUS';
export const MODAL_OPEN_LOGOUT       = 'MODAL_OPEN_LOGOUT';
